
Vagrant.configure("2") do |config|
    config.vm.box = "spox/ubuntu-arm" 
    config.vm.box_version = "1.0.0"
    
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.network "forwarded_port", guest: 80, host: 8082

    config.vm.define "aahrachS" do |vm|
        vm.vm.hostname = "aahrachS"
        vm.vm.provider "vmware_desktop" do |pr|
            pr.allowlist_verified = true
            pr.memory = 1024
            pr.cpus = 1
        end
        vm.vm.provision "shell", path: "scripts/server.sh"
    end
end
