# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/alpine318"
    config.vm.synced_folder ".", "/vagrant"

    # Server Machine
    config.vm.define "aahrachS" do |ser|
        ser.vm.hostname = "aahrachS"
        ser.vm.network "private_network", ip: "192.168.56.110"
        ser.vm.provider "virtualbox" do |pr|
            pr.name = "aahrachS"
            pr.memory = 2048
            pr.cpus = 2
        end

    # Script
    config.vm.provision "shell", path: "scripts/server.sh"
    end
end
