Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04" # I will put the latest version here.

  # VM 1
  config.vm.define "aahrachS" do |vm1|
    vm1.vm.hostname = "aahrachS"
    vm1.vm.network "private_network", ip: "192.168.56.110"
    # vm1.vm.provider "virtualbox" do |prl|
    vm1.vm.provider "parallels" do |prl|
      prl.name = "aahrachS"
      prl.memory = 512
      prl.cpus = 1
    end
  end

  # VM 2
  config.vm.define "aahrachSW" do |vm2|
    vm2.vm.hostname = "aahrachSW"
    vm2.vm.network "private_network", ip: "192.168.56.111"
    vm2.vm.provider "parallels" do |prl|
      prl.name = "aahrachSW"
      prl.memory = 512
      prl.cpus = 1
    end
  end
end

