
Vagrant.configure("2") do |config|

    server_ip = "192.168.56.110"
    worker_ip = "192.168.56.111"
    
    config.vm.define "aahrachS" do |vm1|
        vm1.vm.box = "debian/bookworm64"
        vm1.vm.hostname = "aahrachS"
        vm1.vm.network "private_network", ip: server_ip
        vm1.vm.provider "virtualbox" do |prl|
            prl.memory = 1024
            prl.cpus = 1
        end
        vm1.vm.provision "shell", path: "scripts/server.sh", args: [server_ip]
    end

    config.vm.define "aahrachSW" do |vm2|
        vm2.vm.box = "debian/bookworm64"
        vm2.vm.hostname = "aahrachSW"
        vm2.vm.network "private_network", ip: worker_ip
        vm2.vm.provider "virtualbox" do |prl|
            prl.memory = 1024
            prl.cpus = 1
        end
        vm2.vm.provision "shell", path: "scripts/agent.sh", args: [server_ip]
    end
end
