apiVersion: v1
kind: Service
metadata:
  name: app1-src
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: app2-src
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


apiVersion: v1
kind: Service
metadata:
  name: app3-src
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080